### ISSUE TITLE
Too many requests and DeepL blocked my IP

### ISSUE THREAD

**Issue by bikmanwei** [OwO-Network/PyDeepLX#13]
Hi Vincent, 

Indeed you build a great tool in python and very friendly to use! Thank you. 

I have encountered a problem lately when translating text multiple times using Python. After about 3-5 translations, my requests to the API get rejected. On some occasions, I receive an error code 400. Meanwhile, I have also noticed that the DeepL app on my Mac displays the same information and prevents me from translating anything within the app.

I want to assure you that I have not been sending an excessive number of requests. I was wondering if you are aware of this issue and if there is a solution available. I would greatly appreciate any assistance you can provide.

Bikman

**Comment by XDUcy** [comment]
I'm guessing the problem might be the para `id`. Randomly generating a number between a range might not be a proper way..

**Comment by missuo** [comment]
> I'm guessing the problem might be the para `id`. Randomly generating a number between a range might not be a proper way..

That's exactly what the official app does.

**Comment by ILG2021** [comment]
So it can be solved now? I am still afraid to use this package. I need a steady version.

**Comment by missuo** [comment]
> So it can be solved now? I am still afraid to use this package. I need a steady version.

What I want to tell you is that there cannot be a steady version because this is freeloading DeepL service, and you haven't paid. If you try to frequently request using the DeepL client, your IP will still be banned.

**Comment by ILG2021** [comment]
> > So it can be solved now? I am still afraid to use this package. I need a steady version.
> 
> What I want to tell you is that there cannot be a steady version because this is freeloading DeepL service, and you haven't paid. If you try to frequently request using the DeepL client, your IP will still be banned.

If I use it in a speech translate software, is it ok? not that frequent.

**Comment by bikmanwei** [comment]
Well, I have not try it second time, but after 24~48 hours, the DeepL app works again. So feel free to try this package, the risk is no DeepL in 2 days. Please let us know your results😹

**Comment by missuo** [comment]
> Well, I have not try it second time, but after 24~48 hours, the DeepL app works again. So feel free to try this package, the risk is no DeepL in 2 days. Please let us know your results😹

It's usually not blocked for that long, a couple hours at most.

**Comment by ILG2021** [comment]
I have test the request. i tried to send 10 requests, every request will wait 2s, when I send 3 request, it will crash and said my ip is block. But it doesn't. When I restart the test, it is the same I could only send about 3 requests.

**Comment by oifj34f34f** [comment]
Looks like the problem is still here, although everything works with [DeepLX](https://github.com/OwO-Network/DeepLX). Can we reopen the issue?

**Comment by bikmanwei** [comment]
please close the case. problem no long exist

Kind regards, Bikman Wei Sent from iPhone.


oifj34f34f ***@***.***>于2024年5月10日 周五13:36写道：
