### ISSUE TITLE
Doesn't work with Python 3.12

### ISSUE THREAD

**Issue by eXpressionist** [OwO-Network/PyDeepLX#14]
After I've ran just this string `from PyDeepLX import PyDeepLX`
It gives me an error
_Process finished with exit code -1073740791 (0xC0000409)_

How could we debug this issue?

**Comment by missuo** [comment]
#16

**Comment by eXpressionist** [comment]
![image](https://github.com/OwO-Network/PyDeepLX/assets/5430284/35e6fc90-5dbd-48a4-874c-10a2323b4068)
installed new build, still isn't working

**Comment by missuo** [comment]
> ![image](https://private-user-images.githubusercontent.com/5430284/299461484-35e6fc90-5dbd-48a4-874c-10a2323b4068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMzEyNTksIm5iZiI6MTcwNjEzMDk1OSwicGF0aCI6Ii81NDMwMjg0LzI5OTQ2MTQ4NC0zNWU2ZmM5MC01ZGJkLTQ4YTQtODc0Yy0xMGEyMzIzYjQwNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMjExNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYyYWIwODY0NGNhNDI5YmRiOWU5ZTk0NDY5ODk5MTljZTdjZWI1YTg4NzkzM2Y0YWNhNGI3ZTI3MzRlMmJjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BcQnbfQplpxDV0iqGpd2_rYeEtoJb7YNGOcG-BFk1pw) installed new build, still isn't working

Your code is incorrect.

**Comment by eXpressionist** [comment]
What had I wrote above that Python isn't allowing? 
Of course I've tried samples from readme. I've just wanted to show that it crashes on import somehow (after about 1-2 seconds of running)

![image](https://github.com/OwO-Network/PyDeepLX/assets/5430284/1ec6e43d-24ac-44bb-b24a-174c9f0dba4f)

**Comment by missuo** [comment]
<img width="966" alt="image" src="https://github.com/OwO-Network/PyDeepLX/assets/55200481/dae0164e-3861-4838-aa1a-136f9fb7399b">

**Comment by eXpressionist** [comment]
My point is, it just crashes on import, not because I've improperly used it. 

![image](https://github.com/OwO-Network/PyDeepLX/assets/5430284/46511b99-33a9-459f-9e5e-d892712b5568)

**Comment by jaum20** [comment]
I have the same problem. Crashing on import

**Comment by missuo** [comment]
> I have the same problem. Crashing on import

Any screenshot?

**Comment by jaum20** [comment]
> > I have the same problem. Crashing on import
> 
> Any screenshot?

Sorry, I was importing grom srtranslate package

`from srtranslator.translators.pydeeplx import PyDeepLX`

but now I found that `import PyDeepLX` is working fine
