### ISSUE TITLE
不加proxies参数提示报错

### ISSUE THREAD

**Issue by baiwei0703** [OwO-Network/PyDeepLX#21]
使用仓库中提供的例子安装后运行直接保存，报错截图如下
![image](https://github.com/user-attachments/assets/02fac455-2a8d-42a5-b085-ec775751348e)
希望解决一下

**Comment by vikyathkamathd** [comment]
The issue can be fixed by installing older `httpx` version. I have version 0.16.1 installed. You can do this by running the following command:

```bash
pip install httpx==0.16.1
```


This is a temporary fix until the developer updates the code to work with the latest httpx.

**Comment by baiwei0703** [comment]
> > 使用仓库中提供的例子安装后运行直接保存，报错截图如下 ![image](https://private-user-images.githubusercontent.com/34114426/393083840-02fac455-2a8d-42a5-b085-ec775751348e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzY0NDIsIm5iZiI6MTczMzQ3NjE0MiwicGF0aCI6Ii8zNDExNDQyNi8zOTMwODM4NDAtMDJmYWM0NTUtMmE4ZC00MmE1LWIwODUtZWM3NzU3NTEzNDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOGJjNjg5ZWI4OWM2ZjAwZGYwZjU4NWQyY2ZkY2I3OTJhMGE3ZjMyYmQ2NmE1MzI2MjNhNTU2MTMzNTE4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.11NnyfDImDcCUIwPCgiwQA80tq7w-0VMqblOa-oTJYY) 希望解决一下
> 
> The issue can be fixed by installing an older `httpx` version. I have version 0.16.1 installed. You can do this by running the following command:
> 
> ```shell
> pip install httpx==0.16.1
> ```
> 
> This is a temporary fix until the developer updates the code to work with the latest `httpx`.

It workes!

**Comment by baiwei0703** [comment]
Thank you for your answer
