### ISSUE TITLE
How to avoid error http 429?

### ISSUE THREAD

**Issue by cgapk123** [OwO-Network/PyDeepLX#5]
I have a text that needs to be fully translated at one time. After using the api for two minutes, an error 429 is reported. I try to add a translation every two seconds, but it still can’t be solved. It takes five minutes to fully translate the text, and an error 429 is reported before it is completed.

**Comment by comienzo2093** [comment]
The 429 error can be avoided by using a proxy

**Comment by cgapk123** [comment]
> 使用代理可以避免 429 错误



> The 429 error can be avoided by using a proxy

Hello, is there any free proxy interface or url?
Sorry, I have searched for a long time, but there is not a free multi-proxy address.
