### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by shuibingxin** [OwO-Network/PyDeepLX#6]
![image](https://github.com/OwO-Network/PyDeepLX/assets/12153172/861b4753-eb41-4f3e-b94b-0f7774880b88)

pip install PyDeepLX Tools 

exe this cmd:
python PyDeepLX.py -t "what's wrong whit you?" -s EN -d ZH

but noting happened~

**Comment by missuo** [comment]
No support for command-line passing of parameters
